sudo: required
services: docker
before_install: 
  - sudo pip install csup
  - export RPRE=stevemcgrath 
  - export RNAME=nessus_scanner
script: 
  - docker build --no-cache . -t nessus_scanner:latest
#  - |
#    csup upload nessus_scanner --tag latest \
#      --consec-name sensors/nessus --consec-tag latest -rp
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master                